/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.AirportControleur;
import javax.swing.JOptionPane;

/**
 *
 * @author Formation
 */
public class NewAirport extends javax.swing.JPanel {
    private AirportControleur airportControleur;

    /**
     * Creates new form NewAeroport
     */
    public NewAirport(AirportControleur airportControleur) {
        this.airportControleur = airportControleur;
        
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabelPays = new javax.swing.JLabel();
        jLabel_AITA = new javax.swing.JLabel();
        jLabelVille = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jt_aita = new javax.swing.JTextField();
        jt_city = new javax.swing.JTextField();
        jt_country = new javax.swing.JTextField();
        pb_valider = new javax.swing.JButton();
        pb_annuler = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(1000, 691));
        setMinimumSize(new java.awt.Dimension(1000, 691));
        setPreferredSize(new java.awt.Dimension(1000, 691));
        setLayout(new java.awt.GridBagLayout());

        jLabelPays.setText("Pays");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 77;
        gridBagConstraints.ipady = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(19, 0, 20, 0);
        add(jLabelPays, gridBagConstraints);

        jLabel_AITA.setText("Code AITA");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 77;
        gridBagConstraints.ipady = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(19, 0, 20, 0);
        add(jLabel_AITA, gridBagConstraints);

        jLabelVille.setText("Ville");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 77;
        gridBagConstraints.ipady = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(19, 0, 20, 0);
        add(jLabelVille, gridBagConstraints);

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Nouvel aeroport");
        jLabel4.setMaximumSize(new java.awt.Dimension(450, 54));
        jLabel4.setMinimumSize(new java.awt.Dimension(450, 54));
        jLabel4.setPreferredSize(new java.awt.Dimension(450, 54));
        jLabel4.setVerifyInputWhenFocusTarget(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(40, 0, 40, 0);
        add(jLabel4, gridBagConstraints);

        jt_aita.setMaximumSize(new java.awt.Dimension(10, 24));
        jt_aita.setMinimumSize(new java.awt.Dimension(10, 24));
        jt_aita.setPreferredSize(new java.awt.Dimension(10, 24));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 77;
        gridBagConstraints.ipady = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 35, 0, 34);
        add(jt_aita, gridBagConstraints);

        jt_city.setMaximumSize(new java.awt.Dimension(150, 24));
        jt_city.setMinimumSize(new java.awt.Dimension(150, 24));
        jt_city.setPreferredSize(new java.awt.Dimension(150, 24));
        jt_city.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jt_cityActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 77;
        gridBagConstraints.ipady = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 35, 0, 34);
        add(jt_city, gridBagConstraints);

        jt_country.setMaximumSize(new java.awt.Dimension(150, 24));
        jt_country.setMinimumSize(new java.awt.Dimension(150, 24));
        jt_country.setOpaque(false);
        jt_country.setPreferredSize(new java.awt.Dimension(150, 24));
        jt_country.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jt_countryActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 77;
        gridBagConstraints.ipady = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 35, 0, 34);
        add(jt_country, gridBagConstraints);

        pb_valider.setText("Valider");
        pb_valider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pb_validerActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipadx = 77;
        gridBagConstraints.ipady = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(19, 0, 20, 0);
        add(pb_valider, gridBagConstraints);

        pb_annuler.setText("Annuler");
        pb_annuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pb_annulerActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipadx = 78;
        gridBagConstraints.ipady = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(34, 35, 35, 35);
        add(pb_annuler, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void pb_validerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pb_validerActionPerformed

    boolean result = this.airportControleur.create(jt_aita.getText(), jt_city.getText(), jt_country.getText());
       
        if(result){
                JOptionPane.showMessageDialog(null, "nouveau Airport créer");
        }else{
            JOptionPane.showMessageDialog(null, "erreur");
        }
        
    }//GEN-LAST:event_pb_validerActionPerformed

    private void pb_annulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pb_annulerActionPerformed
        jt_aita.setText("");
        jt_city.setText("");
        jt_country.setText("");
    }//GEN-LAST:event_pb_annulerActionPerformed

    private void jt_cityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jt_cityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jt_cityActionPerformed

    private void jt_countryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jt_countryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jt_countryActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelPays;
    private javax.swing.JLabel jLabelVille;
    private javax.swing.JLabel jLabel_AITA;
    private javax.swing.JTextField jt_aita;
    private javax.swing.JTextField jt_city;
    private javax.swing.JTextField jt_country;
    private javax.swing.JButton pb_annuler;
    private javax.swing.JButton pb_valider;
    // End of variables declaration//GEN-END:variables
}
